export const fields = {
  "teamname": {
    label: "team name",
    type: 'string',
    required: true,
  },
  "people": {
    required: true,
  },
  "created": {
    label: "created on",
    type: 'date',
    required: true,
    disableForForm: true,
  },
  "people": {
    type: 'avatars',
    label: 'assign people',
    entity: 'admin',
    required: true,
    redirectLabel: 'Add New People',
    withRedirect: true,
    urlToRedirect: '/members',
    displayLabels: ['firstname', 'lastname'],
    searchFields: 'firstname,lastname',
    dataIndex: ['people', 'firstname'],
    feedback: 'people',
  },
  // people: {
  //   type: 'search',
  //   label: 'people',
  //   entity: 'people',
  //   redirectLabel: 'Add New Person',
  //   withRedirect: true,
  //   urlToRedirect: '/people',
  //   displayLabels: ['firstname', 'lastname'],
  //   searchFields: 'firstname,lastname',
  //   dataIndex: ['people', 'firstname'],
  //   disableForTable: true,
  //   feedback: 'people',
  // },
  // company: {
  //   type: 'search',
  //   label: 'company',
  //   entity: 'company',
  //   redirectLabel: 'Add New Company',
  //   withRedirect: true,
  //   urlToRedirect: '/company',
  //   displayLabels: ['name'],
  //   searchFields: 'name',
  //   dataIndex: ['company', 'name'],
  //   disableForTable: true,
  //   feedback: 'company',
  // },
};
